export enum SettingsEnum {
  MOD_RELEASE = 'modRelease',
  OPENAI_MODEL = 'openaiModel',
  NOVELAI_MODEL = 'novelaiModel',
  MODS_DIRECTORY = 'modsDirectory',
  CUSTOM_LLM_ENABLED = 'customLLMEnabled',
  AI_API_TYPE = 'aiApiType',
  CUSTOM_LLM_HOSTNAME = 'customLLMHostname',
  ACCESS_TOKEN = 'accessToken',
  OPENAI_KEY = 'openaiKey',
  NOVELAI_KEY = 'novelaiKey',
  LOCALIZATION_ENABLED = 'localizationEnabled',
  LOCALIZATION_LANGUAGE = 'localizationLanguage',
  DEBUG_LOGS = 'debugLogs',
  NSFW_ENABLED = 'nsfwEnabled',
  MAPPING_NOTIFICATION_ENABLED = 'mappingNotificationEnabled',
}
