export enum SettingsEnum {
  MOD_RELEASE = 'modRelease',
  OPENAI_MODEL = 'openaiModel',
  NOVELAI_MODEL = 'novelaiModel',
  SENTIENTSIMSAI_MODEL = 'sentientsimsAIModel',
  MODS_DIRECTORY = 'modsDirectory',
  AI_API_TYPE = 'aiApiType',
  ACCESS_TOKEN = 'accessToken',
  OPENAI_KEY = 'openaiKey',
  NOVELAI_KEY = 'novelaiKey',
  LOCALIZATION_ENABLED = 'localizationEnabled',
  LOCALIZATION_LANGUAGE = 'localizationLanguage',
  DEBUG_LOGS = 'debugLogs',
  NSFW_ENABLED = 'nsfwEnabled',
  MAPPING_NOTIFICATION_ENABLED = 'mappingNotificationEnabled',
  OPENAI_ENDPOINT = 'openaiEndpoint',
  VLLM_ENDPOINT = 'vllmEndpoint',
  VLLM_APIKEY = 'vllmKey',
  VLLM_MODEL = 'vllmModel',
  KOBOLDAI_ENDPOINT = 'koboldAIEndpoint',
  SENTIENTSIMSAI_ENDPOINT = 'sentientsimsAIEndpoint',
  NOVELAI_ENDPOINT = 'novelAIEndpoint',
  NOVELAI_GENERATION_ENDPOINT = 'novelAIGenerationEndpoint',
  GEMINI_KEYS = 'geminiKeys', // Supports multiple keys separated by commas (e.g., "key1,key2,key3")
  GEMINI_ENDPOINT = 'geminiEndpoint',
  GEMINI_MODEL = 'geminiModel',
  TRAIT_MAPPING_PATH = 'traitMappingPath',
  TTS_ENABLED = 'ttsEnabled',
  TTS_API_TYPE = 'ttsApiType',
  TTS_VOLUME = 'ttsVolume',
  OPENAI_TTS_SETTINGS = 'openaiTtsSettings',
  SENTIENTSIMSAI_TTS_SETTINGS = 'sentientsimsaiTtsSettings',
  KOKOROAI_ENDPOINT = 'kokoroaiEndpoint',
  KOKOROAI_TTS_SETTINGS = 'kokoroaiTtsSettings',
  ELEVENLABS_KEY = 'elevenlabsKey',
  ELEVENLABS_ENDPOINT = 'elevenlabsEndpoint',
  ELEVENLABS_TTS_SETTINGS = 'elevenlabsTtsSettings',
  SETUP_WIZARD_PAGE = 'setupWizardPage',
  PATREON_LINKING = 'patreonLinking',
}

export enum DeprecatedSettingsEnum {
  CUSTOM_LLM_ENABLED = 'customLLMEnabled',
}
