export enum TraitType {
  NONE = 'NONE',
  PERSONALITY = 'PERSONALITY',
  GAMEPLAY = 'GAMEPLAY',
  WALKSTYLE = 'WALKSTYLE',
  HIDDEN = 'HIDDEN',
  GHOST = 'GHOST',
  ASPIRATION = 'ASPIRATION',
  TAILSTYLE = 'TAILSTYLE',
  GENDER_OPTIONS = 'GENDER_OPTIONS',
  SIM_PHONE = 'SIM_PHONE',
  PHASE = 'PHASE',
  AGENT = 'AGENT',
  INFECTION = 'INFECTION',
  CURSE = 'CURSE',
  ROOMMATE = 'ROOMMATE',
  ROBOT_MODULE = 'ROBOT_MODULE',
  ROBOT = 'ROBOT',
  PROFESSOR = 'PROFESSOR',
  UNIVERSITY_DEGREE = 'UNIVERSITY_DEGREE',
  ROBOT_MODULE_LOCKED = 'ROBOT_MODULE_LOCKED',
  BATUU_ALIEN = 'BATUU_ALIEN',
  LIFESTYLE = 'LIFESTYLE',
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
  FOOD_RESTRICTION = 'FOOD_RESTRICTION',
  TRADITION = 'TRADITION',
  TEMPERAMENT = 'TEMPERAMENT',
  PACK_MEMBER = 'PACK_MEMBER',
  PACK_FRIEND = 'PACK_FRIEND',
  FEAR = 'FEAR',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  GAMEPLAY_OBJECT_PREFERENCE = 'GAMEPLAY_OBJECT_PREFERENCE',
  INFANT_CARRIER = 'INFANT_CARRIER',
  GAMEPLAY_GENERIC = 'GAMEPLAY_GENERIC',
  HORSE_ACCOLADE = 'HORSE_ACCOLADE',
}

export function toTraitType(someString?: string): TraitType {
  if (Object.values(TraitType).includes(someString as TraitType)) {
    return someString as TraitType;
  }

  throw Error(`Unknown TraitType ${someString}`);
}
