// GENERATED by scripts/gen-tier-index.ts --tier core. Do not edit by hand.
// The committed form is the dev one; a stripped build regenerates it for its tier.
import type { Tier, TierRegistration } from './types';

export const TIER: Tier = 'core';
export const TIER_STAMP = 'sentient-sims-tier:core';
export const TIER_REGISTRATIONS: TierRegistration[] = [];
