export const traitDescriptions: Map<String, string> = new Map(
  Object.entries({
    'absent-minded':
      'gets lost in their thoughts and occasionally forget what they are doing, or where they are going',
    active: 'is active',
    Activities_Acting: 'activities related to acting',
    Activities_Baking: 'baking activities',
    Activities_Bowling: 'bowling activities',
    Activities_Comedy: 'comedy activities',
    Activities_Cooking: 'cooking activities',
    Activities_CrossStitch: 'cross-stitch activities',
    Activities_Dancing: 'dancing',
    Activities_Debating:
      'activities related to debating due to their preference for research and debate',
    Activities_DJMixing: 'DJ Mixing activities',
    Activities_EquestrianSkill:
      'activities related to the Equestrian Skill, such as horse riding',
    Activities_Fishing: 'fishing',
    Activities_Fitness: 'fitness activities',
    Activities_Gardening: 'gardening activities',
    Activities_Guitar: 'playing the guitar',
    Activities_Handiness: 'skilled at practical physical tasks',
    Activities_Knitting: 'knitting activities',
    Activities_MediaProduction: 'media production activities',
    Activities_Mischief: 'mischievous activities',
    Activities_Mixology: 'Mixology activities',
    Activities_NectarMaking: 'activities related to nectar making',
    Activities_Painting: 'painting activities',
    Activities_Photography: 'photography',
    Activities_Piano: 'playing the piano',
    Activities_PipeOrgan: 'playing the pipe organ',
    Activities_Programming: 'programming activities',
    Activities_Robotics: 'activities related to robotics',
    Activities_RockClimbing: 'rock climbing activities',
    Activities_RocketScience: 'activities related to Rocket Science',
    Activities_Singing: 'singing',
    Activities_Skiing: 'skiing',
    Activities_Snowboarding: 'snowboarding activities',
    Activities_VideoGaming: 'video gaming',
    Activities_Violin: 'playing the violin',
    Activities_Wellness: 'activities related to wellness',
    Activities_Writing: 'writing activities',
    Adventurous: 'is adventurous',
    Alluring: 'is alluring',
    AlwaysWelcome: "is always welcome in other people's homes",
    Ambitious: 'is ambitious',
    AnglersTranquility: "is Angler's Tranquility",
    Animal_Attraction: 'is an animal attraction',
    Animal_Whisperer: 'is an animal whisperer',
    AnimalEnthusiast: 'is an animal enthusiast',
    Antiseptic: 'is antiseptic',
    Amusing: 'is amusing',
    Appraiser: 'is an appraiser',
    ArchaeologyScholar_MuseumPatron:
      'is an Archaeology Scholar and Museum Patron',
    ArtLover: 'is an Art Lover',
    Asocial:
      'is asocial, not interested in forming social groups or connections',
    Bane: 'is a bane',
    Barfly: 'is happy when at a bar, Lounge or Nightclub',
    BeachBum_LaidBack: 'is Laid-Back and never becomes tense',
    Beguiling: 'is beguiling',
    Bookworm: 'is a bookworm',
    Boring: 'is boring',
    Brave: 'is brave',
    Bro: 'is a bro',
    Business_Savvy: 'is business savvy',
    Carefree: 'is carefree',
    Captivating: 'is captivating',
    CAS_Story_Career_Activist: 'is a Career Activist',
    CAS_Story_Career_Activist_Level_2: 'is an activist at level 2',
    CAS_Story_Career_Activist_Level_3: 'is an activist',
    CAS_Story_Career_Actor:
      'is a talented actor, bringing characters to life on stage and screen',
    CAS_Story_Career_Actor_Level_2:
      'is a talented actor, bringing characters to life on stage or screen',
    CAS_Story_Career_Actor_Level_3:
      'is a talented actor, bringing characters to life with their energy and charisma',
    CAS_Story_Career_Astronaut: 'is an astronaut',
    CAS_Story_Career_Astronaut_Level_2: 'is an aspiring astronaut',
    CAS_Story_Career_Astronaut_Level_3:
      'is an ambitious astronaut, exploring the galaxy as their playground',
    CAS_Story_Career_Athletic:
      'is an athletic powerhouse. They excel in physical strength, speed, endurance, and intelligence. Their impressive skills and achievements make them a beloved figure among enthusiastic fans, who constantly cheer for them, wear their jersey, and admire their accomplishments',
    CAS_Story_Career_Athletic_2:
      'is a dedicated athlete, possessing immense physical strength, speed, endurance, and intelligence. They are admired by enthusiastic fans who cheer their name, proudly wear their jersey, and forever remember their remarkable achievements',
    CAS_Story_Career_Athletic_3:
      'is a top-level athlete, with exceptional physical abilities and a dedicated fan base',
    CAS_Story_Career_Business:
      'is a business-minded individual with a knack for efficiency and planning',
    CAS_Story_Career_Business_Level_2:
      'is ambitious and driven in their business career',
    CAS_Story_Career_Business_Level_3:
      'is a highly efficient and strategic business professional',
    CAS_Story_Career_CivilDesigner: 'is a Civil Designer',
    CAS_Story_Career_CivilDesigner_Level_2:
      'is a Civil Designer, dedicated to planning and designing environmentally-friendly solutions to improve the world',
    CAS_Story_Career_CivilDesigner_Level_3:
      'is a Civil Designer, focused on planning and designing solutions for environmental problems and making the world a better place to live',
    CAS_Story_Career_Conservationist:
      'is a Conservationist, dedicated to protecting and preserving the planet through education and research',
    CAS_Story_Career_Conservationist_Level_2:
      'is passionate about conservation andis determined to make a positive impact on the environment. They are dedicated to educating others and conducting valuable research to help restore and protect ecosystems. With persistence and hard work, they have the potential to create thriving environments and make a significant difference in the world',
    CAS_Story_Career_Conservationist_Level_3:
      'is passionate about conservation and dedicated to making a positive impact on the environment. They are committed to educating others and conducting research to help protect and restore ecosystems',
    CAS_Story_Career_Corporate_0:
      'is a dedicated Salaryperson at the Farseer Data Corporation. They prioritize their career, striving for advancement and working long hours. Despite the demanding nature of their job, they find enjoyment in their morning commutes and evening karaoke sessions',
    CAS_Story_Career_Corporate_Level_2:
      'is dedicated to their corporate career at Farseer Data Corporation andis focused on advancing their position within the company. They prioritize stability, respect, and hard work, with the opportunity to become a Supervisor or an Expert in their field. Despite their hectic work schedule, they also enjoy morning commutes and evening Karaoke',
    CAS_Story_Career_Corporate_Level_3:
      'is a dedicated Salaryperson who prioritizes the needs of the Farseer Data Corporation above all else. They strive for stability, respect, and success in their career, with the opportunity to advance to higher levels such as Supervisor or Expert. Despite the long hours of work, they still find enjoyment in morning commutes and evening Karaoke',
    CAS_Story_Career_Criminal: 'is a career criminal',
    CAS_Story_Career_Criminal_Level_2:
      'is an outlaw with a taste for adventure and a knack for making money',
    CAS_Story_Career_Criminal_Level_3: 'is a notorious Career Criminal',
    CAS_Story_Career_Critic: 'is a Critic',
    CAS_Story_Career_Critic_Level_2:
      'is a level 2 Critic and loves sharing their opinions on a variety of subjects from food to the arts. Others value their insights and pay attention to what they have to say',
    CAS_Story_Career_Critic_Level_3: 'is a Level 3 Critic',
    CAS_Story_Career_Culinary:
      'is ambitious in their culinary career aspirations',
    CAS_Story_Career_Culinary_Level_2:
      'is on their way to becoming a skilled culinary professional',
    CAS_Story_Career_Culinary_Level_3:
      'excels in the culinary career and takes their cooking expertise to another level',
    CAS_Story_Career_Detective: 'is a detective',
    CAS_Story_Career_Detective_Level_2:
      'is a diligent and determined detective',
    CAS_Story_Career_Detective_Level_3:
      'is a dedicated detective, ready to solve any crime that comes their way',
    CAS_Story_Career_Diver: 'is a career diver',
    CAS_Story_Career_Diver_Level_2:
      'is a skilled diver, exploring the depths of the ocean floor',
    CAS_Story_Career_Diver_Level_3:
      'is a Level 3 Diver, exploring the depths of the ocean floor',
    CAS_Story_Career_Doctor:
      "is a doctor who takes care of other people' health and well-being",
    CAS_Story_Career_Doctor_Level_2:
      'is a skilled doctor, tasked with the important job of saving lives and delivering babies. They handle the high-pressure situations with grace and are well-compensated for their expertise',
    CAS_Story_Career_Doctor_Level_3:
      'is a Level 3 Doctor in the medical career',
    CAS_Story_Career_Education:
      'is passionate about education and finds great fulfillment in shaping young minds',
    CAS_Story_Career_Education_Level_2:
      'is a career in Education and finds it rewarding despite the challenges',
    CAS_Story_Career_Education_Level_3: 'is reached Education Level 3',
    CAS_Story_Career_Engineer: 'is an engineer',
    CAS_Story_Career_Engineer_Level_2: 'is a visionary engineer',
    CAS_Story_Career_Engineer_Level_3: 'is a Level 3 Engineer',
    CAS_Story_Career_Entertainer:
      'is an aspiring entertainer, captivating audiences',
    CAS_Story_Career_Entertainer_Level_2:
      'is a Level 2 Entertainer in their career',
    CAS_Story_Career_Entertainer_Level_3:
      'is an aspiring professional entertainer, whether through comedy or music',
    CAS_Story_Career_Fisherman: 'is a fisherman',
    CAS_Story_Career_Fisherman_Level_2:
      'is a skilled fisherman, able to relax by the water and catch fish with ease',
    CAS_Story_Career_Fisherman_Level_3: 'is a level 3 Fisherman',
    CAS_Story_Career_Gardener: 'is the CAS_Story_Career_Gardener trait',
    CAS_Story_Career_Gardener_Level_2:
      'is a knack for gardening and can potentially turn it into a successful career in science or art',
    CAS_Story_Career_Gardener_Level_3:
      'is a green-thumb gardener with potential for success in both science and art',
    CAS_Story_Career_Law:
      'is a career in law andis the opportunity to help others with their legal problems, champion causes, and further the public good',
    CAS_Story_Career_Law_Level_3: 'is ambitious',
    CAS_Story_Career_Lifeguard: 'is a lifeguard',
    CAS_Story_Career_Lifeguard_Level_2: 'is a lifeguard at level 2',
    CAS_Story_Career_Lifeguard_Level_3:
      'is a Level 3 Lifeguard with a passion for swimming, safety, and keeping rambunctious children in line at the beach',
    CAS_Story_Career_Military: 'is military personnel',
    CAS_Story_Career_Military_level_2:
      'is dedicated to their military career and excels in physical fitness and leadership abilities',
    CAS_Story_Career_Military_Level_3:
      'is at the top of the military career track',
    CAS_Story_Career_Painter:
      'is a professional painter, creating hyperreal masterpieces or abstract works of unsettling beauty',
    CAS_Story_Career_Painter_Level_2: 'is a talented painter',
    CAS_Story_Career_Painter_Level_3: 'is a talented painter',
    CAS_Story_Career_Scientist: 'is a scientist',
    CAS_Story_Career_Scientist_Level_2: 'is a brilliant scientist',
    CAS_Story_Career_Scientist_Level_3: 'is a brilliant scientist',
    CAS_Story_Career_Secret_Agent: 'is a secret agent',
    CAS_Story_Career_Secret_Agent_Level_2: 'is a secret agent at level 2',
    CAS_Story_Career_Secret_Agent_Level_3:
      'is a covert operative in the Secret Agent career, specializing in infiltration and interrogation',
    CAS_Story_Career_Social_Media: 'is a social media magnate',
    CAS_Story_Career_Social_Media_Level_2: 'is a social media magnate',
    CAS_Story_Career_Social_Media_Level_3: 'is a Social Media Magnate',
    CAS_Story_Career_Style_Influencer: 'is a professional Style Influencer',
    CAS_Story_Career_Style_Influencer_Level_2:
      'is a level 2 skilled professional Style Influencer',
    CAS_Story_Career_Style_Influencer_Level_3:
      'has reached Level 3 in the Style Influencer career andis a knack for identifying the right colors, trendy patterns, and ensemble pairings to create cohesive looks. They have the power to influence and shape the fashion world',
    CAS_Story_Career_Tech_Guru: 'is a Tech Guru',
    CAS_Story_Career_Tech_Guru_Level_2:
      'is ambitious in their tech career and believes that their programming skills are all they need to succeed. They are confident and ready to seize the opportunities that come their way',
    CAS_Story_Career_Tech_Guru_Level_3: 'is ambitious',
    CAS_Story_Career_Unemployed: 'is currently unemployed',
    CAS_Story_Career_Writer: 'is a Writer',
    CAS_Story_Career_Writer_Level_2:
      'is a talented writer, using their beautiful turns of phrase to express ideas with wonderful words',
    CAS_Story_Career_Writer_Level_3:
      'is a level 3 Writer in the CAS Story Career',
    CAS_Story_Household_Funds_High:
      'is a high household funds trait andis living the good life with plenty of simoleons to spare',
    CAS_Story_Household_Funds_Low: 'has low household funds',
    CAS_Story_Household_Funds_Med: 'has extra household funds to enjoy',
    CAS_Story_Skill_Acting: 'is the CAS_Story_Skill_Acting trait',
    CAS_Story_Skill_Acting_3:
      'is a skilled actor, bringing characters to life and moving others with their storytelling abilities',
    CAS_Story_Skill_Archaeology: 'is an expert in Archaeology',
    CAS_Story_Skill_Archaeology_3:
      'is passionate about archaeology and uncovering ancient artifacts and lost knowledge',
    CAS_Story_Skill_Baking: 'is a skilled baker',
    CAS_Story_Skill_Baking_3:
      'is mastered the art of baking and knows how to create delicious treats with precision and creativity',
    CAS_Story_Skill_Bowling: 'is skilled in bowling',
    CAS_Story_Skill_Bowling_3: 'is the CAS_Story_Skill_Bowling_3 trait',
    CAS_Story_Skill_Charisma: 'is charismatic',
    CAS_Story_Skill_Charisma_3: 'is charismatic',
    CAS_Story_Skill_Comedy: 'is skilled at comedy',
    CAS_Story_Skill_Comedy_3:
      'excels in the skill of comedy and finds humor in everything',
    CAS_Story_Skill_Cooking: 'is epicurious',
    CAS_Story_Skill_Cooking_3: 'is epicurious',
    CAS_Story_Skill_CrossStitch: 'is the Cross-Stitch skill',
    CAS_Story_Skill_CrossStitch_3: 'Cross Stitch Expert',
    CAS_Story_Skill_Dancing: 'is a skilled dancer',
    CAS_Story_Skill_Dancing_3: 'is a skilled dancer',
    CAS_Story_Skill_DJ_Mixing: 'is skilled in DJ Mixing',
    CAS_Story_Skill_DJ_Mixing_3: 'is a skilled DJ',
    CAS_Story_Skill_Entrepreneur: 'is an entrepreneur',
    CAS_Story_Skill_Entrepreneur_3: 'is a high level of the Entrepreneur skill',
    CAS_Story_Skill_EquestrianSkill: 'is the Equestrian Skill trait',
    CAS_Story_Skill_EquestrianSkill_3: 'is the Equestrian Skill',
    CAS_Story_Skill_Fabrication: 'is the CAS_Story_Skill_Fabrication trait',
    CAS_Story_Skill_Fabrication_3:
      'is skilled in fabrication and crafting unique creations using recycled materials',
    CAS_Story_Skill_Fishing: 'is passionate about fishing',
    CAS_Story_Skill_Fishing_3:
      'is skilled in fishing and it so much, they openly admit to being hooked on it',
    CAS_Story_Skill_Fitness: 'is fitness-minded',
    CAS_Story_Skill_Fitness_3: 'is fitness-minded',
    CAS_Story_Skill_Flower_Arranging: 'is mastered the art of Flower Arranging',
    CAS_Story_Skill_Flower_Arranging_3: 'is skilled in flower arranging',
    CAS_Story_Skill_Gardening: 'is skilled in gardening',
    CAS_Story_Skill_Gardening_3: 'is skilled in gardening',
    CAS_Story_Skill_Gourmet_Cooking: 'is a gourmet cook',
    CAS_Story_Skill_Gourmet_Cooking_3: 'is a gourmet cook',
    CAS_Story_Skill_Guitar:
      'has a talent for playing the guitar and can entertain others with their music',
    CAS_Story_Skill_Guitar_3: 'excels at playing the guitar',
    CAS_Story_Skill_Handiness: 'is handy',
    CAS_Story_Skill_Handiness_3: 'is a knack for being handy',
    CAS_Story_Skill_Herbalism: 'is skilled in Herbalism',
    CAS_Story_Skill_Herbalism_3:
      'is advanced skills in Herbalism andis skilled in identifying and using rare and valuable herbs',
    CAS_Story_Skill_JuiceFizzing: 'is a Juice Fizzing enthusiast',
    CAS_Story_Skill_JuiceFizzing_3: 'is a JuiceFizzing enthusiast',
    CAS_Story_Skill_Local_Culture:
      'is a strong passion for Selvadoradian culture',
    CAS_Story_Skill_Local_Culture_3:
      'is passionate about Selvadoradian culture',
    CAS_Story_Skill_Logic: 'is skilled in logic',
    CAS_Story_Skill_Logic_3: 'is highly skilled in logic',
    CAS_Story_Skill_Mischief: 'is mischievous',
    CAS_Story_Skill_Mischief_3: 'is mischievous',
    CAS_Story_Skill_Mixology: 'is skilled in mixology',
    CAS_Story_Skill_Mixology_3:
      'is mastered the art of mixology andis skilled at creating delicious drinks and engaging in friendly conversation',
    CAS_Story_Skill_Nectar: 'is skilled in Nectar Making',
    CAS_Story_Skill_Nectar_3:
      'is skilled in the art of Nectar Making and loves to create unique and flavorful concoctions by smashing ingredients together',
    CAS_Story_Skill_Painting: 'is a skillful painter',
    CAS_Story_Skill_Painting_3: 'is a high skill level in painting',
    CAS_Story_Skill_Parenting: 'is a skilled parent',
    CAS_Story_Skill_Parenting_3: 'is a skilled parent',
    CAS_Story_Skill_Pet_Training: 'is skilled in pet training',
    CAS_Story_Skill_Pet_Training_3: 'is skilled in pet training',
    CAS_Story_Skill_Photography: 'is a skilled photographer',
    CAS_Story_Skill_Photography_3: 'is a talented photographer',
    CAS_Story_Skill_Piano: 'excels at playing the piano',
    CAS_Story_Skill_Piano_3: 'is a skilled pianist',
    CAS_Story_Skill_PipeOrgan: 'is skilled in playing the Pipe Organ',
    CAS_Story_Skill_PipeOrgan_3: 'is skilled at playing the Pipe Organ',
    CAS_Story_Skill_Programming: 'is skilled in programming',
    CAS_Story_Skill_Programming_3: 'is skilled in programming',
    CAS_Story_Skill_ResearchDebate: 'is skilled in research and debate',
    CAS_Story_Skill_ResearchDebate_3:
      'excels in Research & Debate, utilizing information to persuade and influence others',
    CAS_Story_Skill_Robotics:
      'they have a knack for technology and enjoy tinkering with robotics',
    CAS_Story_Skill_Robotics_3:
      'they are skilled in robotics and can create robots for various purposes like chores, protection, and entertainment',
    CAS_Story_Skill_RockClimbing: 'is an adventurous rock climber',
    CAS_Story_Skill_RockClimbing_3: 'is an adventurous rock climber',
    CAS_Story_Skill_Rocket_Science: 'is a master of Rocket Science',
    CAS_Story_Skill_Rocket_Science_3: 'is adventurous',
    CAS_Story_Skill_Singing: 'excels at singing',
    CAS_Story_Skill_Singing_3:
      'is a natural talent for singing and loves to showcase their skills wherever they go',
    CAS_Story_Skill_Skiing:
      'excels in skiing and the thrill of gliding down slopes',
    CAS_Story_Skill_Skiing_3: 'they are skilled in skiing',
    CAS_Story_Skill_Snowboarding: 'is skilled in snowboarding',
    CAS_Story_Skill_Snowboarding_3: 'is skilled in snowboarding',
    CAS_Story_Skill_Vampire_Lore: 'is knowledgeable about vampire lore',
    CAS_Story_Skill_Vampire_Lore_3: 'is a master of Vampire Lore',
    CAS_Story_Skill_Veterinarian: 'is the CAS_Story_Skill_Veterinarian trait',
    CAS_Story_Skill_Veterinarian_3:
      'possesses the CAS_Story_Skill_Veterinarian_3 trait',
    CAS_Story_Skill_Video_Gaming: 'is a skilled video gamer',
    CAS_Story_Skill_Video_Gaming_3: 'is skilled in video gaming',
    CAS_Story_Skill_Violin: 'is a skilled violinist',
    CAS_Story_Skill_Violin_3: 'is skilled in playing the violin',
    CAS_Story_Skill_Wellness: 'is acquired the Wellness trait',
    CAS_Story_Skill_Wellness_3:
      'is acquired the Wellness skill andis skilled at regulating their moods and sensations',
    CAS_Story_Skill_Writing: 'is skilled in the art of writing',
    CAS_Story_Skill_Writing_3: 'is a skilled writer',
    CatLover: 'is a Cat Lover',
    Cauldron_Potion_Immortality: 'is immortal',
    Cauldron_Potion_Luck_Clumsy:
      'is naturally clumsy, often stumbling or tripping over their own feet. However, rather than becoming upset when they fail at physical activities, they find humor in their clumsiness and laugh it off',
    ChampionOfThePeople: 'is a true Champion of the People',
    Characteristic_Ambitionless: 'is ambitionless',
    Characteristic_Argumentative: 'is argumentative',
    Characteristic_Cerebral: 'is cerebral',
    Characteristic_Egotistical: 'is egotistical',
    Characteristic_EmotionalDecisionMaker: 'is an emotional decision-maker',
    Characteristic_Funny: 'is funny',
    Characteristic_HardWorker: 'is a hard worker',
    Characteristic_HighEnergy: 'is high energy',
    Characteristic_Homebody: 'is a homebody',
    Characteristic_Idealist: 'is an idealist',
    Characteristic_KidEnthusiast: 'is a kid enthusiast',
    Characteristic_Mischievous: 'is mischievous',
    Characteristic_NatureEnthusiast: 'is a nature enthusiast',
    Characteristic_Optimist: 'is optimistic',
    Characteristic_Pessimist: 'is pessimistic',
    Characteristic_PetEnthusiast: 'is a pet enthusiast',
    Characteristic_RomanceEnthusiast: 'is a Romance Enthusiast',
    Characteristic_Spirited: 'is spirited',
    Charming: 'is charming',
    Cheerful: 'is cheerful',
    ChildConfidence_High: 'has high confidence',
    ChildConfidence_Low: 'has low confidence',
    ChildConfidence_Neutral: 'has neutral confidence',
    ChildhoodPhase_Bear: 'loves to dress up as a bear',
    ChildhoodPhase_Clingy: 'is clingy',
    ChildhoodPhase_Distant: 'is distant',
    ChildhoodPhase_Loud: 'is loud',
    ChildhoodPhase_MeanStreak: 'has a mean streak',
    ChildhoodPhase_PickyEater_A: 'is a picky eater',
    ChildhoodPhase_PickyEater_B: 'is a picky eater',
    ChildhoodPhase_PickyEater_C: 'is a picky eater',
    ChildhoodPhase_PickyEater_D: 'is a picky eater',
    ChildhoodPhase_PickyEater_DisgustedByFood:
      'is a picky eater and gets disgusted by certain foods',
    ChildhoodPhase_PickyEater_E: 'is a picky eater',
    ChildhoodPhase_Rebellious: 'is rebellious',
    Childish: 'is childish',
    ChildoftheOcean: 'is a child of the ocean',
    ChildSkillReward_Headstrong: 'is headstrong',
    ChildSkillReward_IdeaPerson: 'is an idea person',
    ChildSkillReward_PackAnimal:
      'excels at training and improving both themselves and others when working with friends',
    ChildSkillReward_PraticedHost: 'is a practiced host',
    ChopstickSavvy: 'is chopstick savvy',
    Chronicler: 'is a chronicler',
    ClubPresident: 'is the Club President',
    Clumsy: 'is clumsy',
    'Cold-Blooded':
      'is very bold and manipulative, deceiving others with calm and focused demeanour',
    ColdHearted: 'is cold-hearted',
    Collector: 'is a Collector',
    Comforting: 'is comforting to be around',
    Color_Black: 'the color black',
    Color_Blue: 'the color blue',
    Color_Brown: 'the color brown',
    Color_Gray: 'the color gray',
    Color_Green: 'the color green',
    Color_Orange: 'the color orange',
    Color_Pink: 'the color pink',
    Color_Purple: 'the color purple',
    Color_Red: 'the color red',
    Color_White: 'the color white',
    Color_Yellow: 'the color yellow',
    CommitmentIssues: 'has commitment issues',
    Communication_Affection: 'communication and affection',
    Communication_Arguments:
      'engaging in arguments and finds communication through disagreements stimulating',
    Communication_Complaints:
      'is a preference for communication and tends to express complaints more often',
    Communication_Compliments: 'communication that involves giving compliments',
    Communication_Deception: 'and engaging in deceptive communication',
    Communication_DeepThoughts:
      'is a preference for deep and meaningful conversations',
    Communication_Flirtation: 'to communicate through flirtation',
    Communication_Gossip:
      'gossiping and discussing the latest news with other people',
    Communication_Hobbies: 'to discuss hobbies with others',
    Communication_Interests: 'discussing interests',
    Communication_Jokes: 'communication through jokes',
    Communication_Malicious: 'is a preference for malicious interactions',
    Communication_PhysicalIntimacy:
      'physical intimacy andis likely to seek out opportunities for affectionate interactions',
    Communication_PottyHumor: 'is a preference for potty humor',
    Communication_Pranks: 'pulling pranks on others',
    Communication_SillyBehavior: 'engaging in silly behavior',
    Communication_SmallTalk: 'engaging in small talk with others',
    Communication_Stories: 'engaging in conversations and storytelling',
    Connections: 'has connections and starts careers several levels ahead',
    CorporateWorker_CharismaticCrooner:
      'is a charismatic crooner, skilled in using their vocal tones to build better relationships with co-workers and enhance their singing ability',
    CorporateWorker_LegendaryStamina: 'is legendary stamina',
    Coward: 'is a coward, terrified of everything',
    Crazy: 'is wild and fun loving, would do anything for love',
    Creative: 'is creative',
    CreativelyGifted: 'is creatively gifted',
    CreativeVisionary: 'is a creative visionary',
    Creepy: 'is creepy and makes others uncomfortable',
    Curses_FountainOfMagic:
      'is cursed by the Fountain of Magic andis able to draw an excessive amount of magical energy, resulting in increased gains',
    Curses_HexOfDuelist: 'is cursed with the Hex of the Duelist',
    Curses_InfectiousLaughter: 'is cursed with infectious laughter',
    Curses_NightStalker: 'is terrorized by a night stalker',
    Curses_PunchableFace: 'is cursed with a punchable face',
    Curses_Repulsiveness: 'is cursed with repulsiveness',
    Curses_SweatyStench: 'is cursed to always have a sweaty stench',
    Curses_TouchyFeely: 'is touchy-feely',
    Curses_WildMagic: 'has a wild magic curse',
    DanceMachine: 'is a Dance Machine',
    Dastardly: 'is dastardly',
    Dauntless: 'is dauntless',
    Daredevil:
      'is reckless and daring, is confident and active and unaffected by stress',
    chingyu1023_LovelyTrait_LovelyTrait:
      'is very attractive to their loved ones', // Darling
    Decor_ArtDeco: 'Art Deco decor',
    Decor_Basics: 'basic decor',
    Decor_Boho: 'Boho decor',
    Decor_Contemporary: 'contemporary decor',
    Decor_Cosmolux: 'Cosmolux decor',
    Decor_Cute: 'cute decor',
    Decor_FrenchCountry: 'French Country decor',
    Decor_Garden: 'garden decor',
    Decor_GothicFarmhouse: 'Gothic Farmhouse decor',
    Decor_Industrial: 'industrial decor',
    Decor_Island: 'island decor',
    Decor_Luxe: 'luxe decor',
    Decor_Mission: 'Mission decor',
    Decor_Modern: 'modern decor',
    Decor_Patio: 'patio decor',
    Decor_QueenAnne: 'Queen Anne decor',
    Decor_ScandinavianContemporary:
      'Scandinavian contemporary decor and mid-century style',
    Decor_Shabby: 'shabby decor',
    Decor_SuburbanContempo: 'suburban contemporary decor',
    Decor_Tudor: 'Tudor-style decor',
    Decor_Vintage: 'vintage decor',
    Delightful: 'is pleasant to be with',
    Detached: 'has delayed emotional response to extreme emotions',
    Determined: 'does not allow any difficulties to stop them',
    Diffident: 'lacks confidence in their abilities and decisions',
    'Disliking Children':
      'gets tense around kids because they find kids annoying',
    'Disliking Elders': 'gets bored around elders',
    Doctor_SicknessResistant: 'is sickness resistant',
    DogLover: 'is a dog lover',
    Downer: 'constantly makes others feel bad',
    Eccentric: 'is eccentric',
    eco_master: 'is an eco master',
    EcoEngineer: 'is an Eco-Engineer',
    Emotional: 'is emotional and highly sensitive',
    Encouraging: 'is very supporting of their friends, loved ones and family',
    entrepreneur: 'is an entrepreneur',
    Entrepreneur_TheKnowledge: 'is an Entrepreneur with the Knowledge trait',
    Entrepreneurial: 'is entrepreneurial',
    Envious: 'is envous',
    EpicPoet: 'is an Epic Poet',
    EssenceOfFlavor: 'is the Essence of Flavor trait',
    EternalBond: 'has an Eternal Bond with their spouse',
    Evil: 'is Evil',
    Evil_BegoniaScent: 'is the Evil_BegoniaScent trait',
    Excitable: 'is quick to respond to anything new or stimulating',
    Excursion_Mountaineer_Rank1: 'is an Excursion Mountaineer Rank 1',
    Excursion_Mountaineer_Rank2:
      'is an experienced mountaineer, with a good knowledge of climbing routes and greater success in outdoor activities',
    Excursion_Mountaineer_Rank3: 'is an Excursion Mountaineer Rank 3',
    Expressionistic: 'is expressionistic',
    Extrovert: 'is an extrovert',
    FakeGenius: 'is temporarily a fake genius',
    FamilyOriented: 'is family-oriented',
    FamilySim: 'is family-oriented',
    Fashion_Basics: 'basic fashion',
    Fashion_Boho: 'Boho Fashion',
    Fashion_Country: 'country fashion',
    Fashion_Hipster: 'hipster fashion',
    Fashion_Outdoorsy: 'outdoorsy fashion',
    Fashion_Polished: 'polished fashion',
    Fashion_Preppy: 'preppy fashion',
    Fashion_Rocker: 'rocker fashion',
    Fashion_Streetwear: 'streetwear fashion',
    FastFastidious: 'is fastidious',
    Fear_BeingCheatedOn: 'fears being cheated on',
    Fear_BeingJudged: 'fears being judged',
    Fear_Cowplant: 'is fearful of Cowplants',
    Fear_CrowdedPlaces: 'is fearful of crowded places',
    Fear_Dark: 'is afraid of the dark',
    Fear_DeadEndJob: 'is fearful about their dead-end job',
    Fear_Death: 'is fearful of death',
    Fear_DisappointingParents: 'is afraid of disappointing their parents',
    Fear_Failing_AfterSchoolActivities:
      'has a fear of failing in after-school activities',
    Fear_Failing_Class:
      'fears failing their classes and occasionally struggles to focus due to the pressure',
    Fear_Failing_Tests: 'is fearful of failing tests',
    Fear_Failure: 'has a fear of failure',
    Fear_Fire: 'is scared of fire',
    Fear_Ghosts: 'is scared of ghosts',
    Fear_Homework: 'is the Fear_Homework trait',
    Fear_Horses: 'is afraid of horses',
    Fear_Horses_Progress: 'is a fear of horses',
    Fear_Inferior: 'is fearful of being inferior',
    Fear_Swimming: 'is fearful of swimming',
    Fear_Unfulfilled: 'is fearful of being unfulfilled',
    Fertile: 'is fertile',
    Fickle: 'is fickle',
    FilthDweller: 'is a Filth Dweller',
    Fizzyhead: 'is a Fizzyhead',
    Foodie: 'is a foodie',
    ForeverFresh: 'is forever fresh',
    ForeverFull: 'is Forever Full',
    Freegan: 'is a Freegan',
    Freelancer_Career_Hidden_Agencies_Fashion_Photographer:
      'is a freelance fashion photographer',
    Freelancer_Career_Hidden_Agencies_Maker:
      'is a Freelancer in the Hidden Agencies Maker trade, specializing in fabricating, juice fizzing, and candle making. They are dedicated to delivering hand-crafted and eco-conscious goods to people',
    Freelancer_Career_Hidden_Agencies_Painting:
      'is a Freelance Artist specializing in Painting',
    Freelancer_Career_Hidden_Agencies_ParanormalInvestigator:
      'is a Paranormal Investigator in the Freelancer Career',
    Freelancer_Career_Hidden_Agencies_Programming:
      'is a hidden talent for freelance programming andis a valuable asset in the field',
    Freelancer_Career_Hidden_Agencies_Writing:
      'is a freelance writer with hidden agency connections',
    Freelancer_Career_ParanormalInvestigator_License:
      'holds a Freelancer Career Paranormal Investigator License',
    FreeServices: 'gets services for free',
    FreshChef: 'is a Fresh Chef',
    FriendOfTheSea: 'is a Friend of the Sea',
    Friendly: 'is friendly, kind and pleasant',
    Frugal: 'is frugal',
    FTUE_CareerMinded_initial: 'is career-minded',
    Geek: 'is a geek',
    Genius: 'is a genius',
    Gentle: 'is sweet and gentle',
    ghost_Anger: 'is a ghost who died by being too angry',
    Ghost_AnimalObjects_KillerChicken: 'has a killer chicken haunting them',
    Ghost_AnimalObjects_KillerRabbit: 'is haunted by a killer rabbit',
    Ghost_Beetle: 'is a Ghost Beetle',
    Ghost_Cauldron_Potion_Immortality_Failure:
      'is experienced a failure in their pursuit of immortality. They are currently in a temporary state of dissatisfaction, but they should try to make the most of their ghostly existence',
    Ghost_ClimbingRoute:
      'embraces their afterlife by fearlessly climbing high surfaces',
    ghost_Cowplant:
      'is a ghost who died by being eaten by a carnivorous Cowplant',
    Ghost_DeathFlower: 'is a ghost who died by a Death Flower',
    ghost_Drown: 'is a ghost who died by drowning',
    ghost_ElderExhaustion:
      'is a ghost who died from becoming exhausted as an Elder',
    ghost_Electrocution: 'is a ghost who died by electrocution',
    ghost_Embarrassment: 'is a ghost who died of embarassment',
    ghost_Fire: 'is a ghost who died in a fire',
    Ghost_Flies: 'is been plagued by ghost flies',
    ghost_Frozen: 'is a ghost who froze to death',
    ghost_Hunger: 'is a ghost who is haunted by hunger even in the afterlife',
    ghost_Laugher: 'is a ghost who died from laughing too hard',
    Ghost_Lightning: 'is a ghost who was struck by lightning and died',
    Ghost_Meteorite: 'is a ghost with a meteorite backstory',
    Ghost_MotherPlant: 'is a ghost who died by a Mother Plant',
    Ghost_MurphyBed: 'is haunted by a vengeful Murphy Bed',
    ghost_OldAge: 'is a ghost who died of old age',
    ghost_Overheat: 'is a ghost who died from overheating',
    Ghost_Poison: 'is a ghost who died by consuming poison',
    Ghost_Pufferfish: 'is a ghost who died by eating a Pufferfish',
    Ghost_Rodent_Disease: 'is a ghost who was killed by a rodent disease',
    Ghost_SeanceTable:
      'is a Ghost with the ability to interact and use a seance table',
    ghost_Steam: 'is a ghost who died by being burned by steam',
    Ghost_StinkBomb: 'is a Ghost_StinkBomb',
    Ghost_UrbanMyth_EP12Death: 'is haunted by an urban myth',
    ghost_Vampire_Sun: 'is a ghost vampire that is sensitive to the sun',
    Ghost_VendingMachine: 'is a ghost vending machine',
    Ghost_WitchOverload: 'is a Ghost Witch Overload',
    Gloomy: 'is gloomy',
    Glutton: 'is a glutton',
    Good: 'is good',
    Goofball: 'is a goofball',
    GreatKisser: 'is a great kisser',
    GreatStoryteller: 'is a great storyteller',
    GreenFiend: 'is a GreenFiend',
    Gregarious: 'is gregarious',
    'Gym Bunny': 'has fun and is energized when at a Gym, Pool or Spa',
    GymRat: 'is a Gym Rat',
    Handedness_Left: 'is left-handed',
    Handedness_Right: 'is right-handed',
    Happy_Toddler: 'is a Happy Toddler',
    HardlyHungry: 'is hardly hungry',
    HatesChildren: 'hates children',
    'Hates Teens': 'gets angry around teens',
    Heroic: 'is heroic, ready to face danger or pain',
    HeroicPresence: 'is a heroic presence',
    HeroOfStrangerville: 'is the Hero of StrangerVille',
    Hidden_ActorCareer_Agency_AIStaffing:
      'is part of the Hidden Actor Career Agency AI Staffing',
    Hidden_ActorCareer_Agency_EverydayExtras:
      "is part of the Hidden Actor Career Agency's Everyday Extras division. They have more auditions for commercials and daytime TV gigs",
    Hidden_ActorCareer_Agency_GRAN:
      'is the Hidden Actor career agency grant trait',
    Hidden_ActorCareer_Agency_WellSuited:
      'is well-suited for the Hidden Actor career agency and excels in drama and action Prime Time TV and Movie gigs',
    Hidden_Career_Critic_Thrifty: 'is a Hidden Career Critic Thrifty',
    Hidden_IslandAncestor_Elemental: 'is a Hiddenisland Ancestor Elemental',
    High_Metabolism: 'has a high metabolism',
    Highflier: 'is a highflier',
    HighFlyer: 'is a High Flyer',
    HighMaintenance: 'is high maintenance',
    'High-Spirited': 'is very energetic and playful',
    'High-Strung': 'gets tense often',
    Hilarious: 'is hilarious',
    HolidayTradition_FatherWinterBaby:
      'is a special familial connection to Father Winter',
    Homebody: 'prefers to spend time at home rather than anywhere else',
    HomeTurf: 'feels connected and content when in their home neighborhood',
    Horse_Gameplay_Curious: 'is curious',
    Horse_Gameplay_EquestrianCenter_ChampionHorse:
      'This horse is a champion! Their foals inherit their skills and determination, making them more valuable',
    Horse_Gameplay_HorseBreeding_ChampionGenes: 'is the Champion Genes trait',
    Horse_Gameplay_Playful: 'is playful',
    Horse_Gameplay_Resilient: 'is resilient',
    Horse_Gameplay_RewardTrait_TopNotchFoal: 'is the Top Notch Foal trait',
    Horse_HorseCompetition_BarrelRacing_Beginner_1st:
      'is a beginner barrel racer andis won 1st place in their first competition',
    Horse_HorseCompetition_BarrelRacing_Beginner_2nd:
      'is a beginner in barrel racing and achieved 2nd place',
    Horse_HorseCompetition_BarrelRacing_Beginner_3rd:
      'is achieved 3rd place in beginner-level barrel racing competitions',
    Horse_HorseCompetition_BarrelRacing_Expert_1st:
      'is an expert barrel racing competitor andis claimed 1st place multiple times',
    Horse_HorseCompetition_BarrelRacing_Expert_2nd:
      'is a skilled barrel racing competitor, consistently finishing in second place',
    Horse_HorseCompetition_BarrelRacing_Expert_3rd:
      'is an expert barrel racing competitor, having achieved 3rd place in competitions',
    Horse_HorseCompetition_BarrelRacing_Intermediate_1st:
      'is a skilled barrel racing competitor, achieving first place in intermediate difficulty levels',
    Horse_HorseCompetition_BarrelRacing_Intermediate_2nd:
      'is an intermediate level barrel racer whois taken 2nd place in competitions',
    Horse_HorseCompetition_BarrelRacing_Intermediate_3rd:
      'is placed 3rd in the Intermediate Difficulty Barrel Racing competition for horses',
    Horse_HorseCompetition_BarrelRacing_Master_1st:
      'is a master at barrel racing, having achieved 1st place in competition',
    Horse_HorseCompetition_BarrelRacing_Master_2nd:
      'is achieved second place in the master level of barrel racing competitions',
    Horse_HorseCompetition_BarrelRacing_Master_3rd:
      'is a skilled barrel racer, achieving 3rd place at the master difficulty level',
    Horse_HorseCompetition_EnduranceRacing_Beginner_1st:
      'is a highly skilled endurance racing competitor, achieving 1st place in the beginner level of the competition',
    Horse_HorseCompetition_EnduranceRacing_Beginner_2nd:
      'is an endurance racing beginner and placed 2nd in their first competition',
    Horse_HorseCompetition_EnduranceRacing_Beginner_3rd:
      'is placed 3rd in a beginner-level endurance racing competition for horses',
    Horse_HorseCompetition_EnduranceRacing_Expert_1st:
      'is an expert in endurance racing andis achieved 1st place',
    Horse_HorseCompetition_EnduranceRacing_Expert_2nd:
      'is an expert in endurance racing andis secured the second place',
    Horse_HorseCompetition_EnduranceRacing_Expert_3rd:
      'is an expert in endurance racing andis achieved 3rd place',
    Horse_HorseCompetition_EnduranceRacing_Intermediate_1st:
      'excels in endurance racing, winning first place in intermediate difficulty',
    Horse_HorseCompetition_EnduranceRacing_Intermediate_2nd:
      'is achieved 2nd place in intermediate difficulty endurance racing competitions',
    Horse_HorseCompetition_EnduranceRacing_Intermediate_3rd:
      'is an intermediate endurance racing competitor, having achieved 3rd place',
    Horse_HorseCompetition_EnduranceRacing_Master_1st:
      'is a master of endurance racing andis achieved 1st place proficiency',
    Horse_HorseCompetition_EnduranceRacing_Master_2nd:
      'is a master in endurance racing, consistently achieving 2nd place in competitions',
    Horse_HorseCompetition_EnduranceRacing_Master_3rd:
      'is a master in endurance racing andis achieved 3rd place',
    Horse_HorseCompetition_NoCompetitionsWon:
      'is not won any competitions at the Hay Now! Equestrian Center in New Appaloosa',
    Horse_HorseCompetition_ShowJumping_Beginner_1st:
      'is a beginner in the horse show jumping competition andis won first place',
    Horse_HorseCompetition_ShowJumping_Beginner_2nd:
      'is a beginner in horse show jumping andis achieved 2nd place in a competition',
    Horse_HorseCompetition_ShowJumping_Beginner_3rd:
      'is achieved 3rd place in the beginner level of show jumping competitions',
    Horse_HorseCompetition_ShowJumping_Expert_1st:
      'is an expert in show jumping andis achieved 1st place',
    Horse_HorseCompetition_ShowJumping_Expert_2nd:
      'is an Expert Show Jumping Competitor whois achieved 2nd place in competitions',
    Horse_HorseCompetition_ShowJumping_Expert_3rd:
      'is a Horse Competition Show Jumping Expert, having achieved 3rd place in their competitions',
    Horse_HorseCompetition_ShowJumping_Intermediate_1st:
      'is the 1st place winner in intermediate level show jumping competitions for horses',
    Horse_HorseCompetition_ShowJumping_Intermediate_2nd:
      'is achieved 2nd place in an intermediate horse show jumping competition',
    Horse_HorseCompetition_ShowJumping_Intermediate_3rd:
      'is placed 3rd in an intermediate-level show jumping competition for horses',
    Horse_HorseCompetition_ShowJumping_Master_1st:
      'is a master at show jumping andis achieved 1st place multiple times in horse competitions',
    Horse_HorseCompetition_ShowJumping_Master_2nd:
      'is a skilled show jumping competitor, consistently achieving second place in competitions',
    Horse_HorseCompetition_ShowJumping_Master_3rd:
      'is a master in show jumping andis achieved 3rd place in competitions',
    Horse_HorseCompetition_UltimateChampionship_1st:
      'is won the Ultimate Horse Championship andis the reigning 1st place champion',
    Horse_HorseCompetition_UltimateChampionship_2nd:
      'is the 2nd place winner of the Ultimate Horse Championship',
    Horse_HorseCompetition_UltimateChampionship_3rd:
      'is earned the title of 3rd place in the Ultimate Horse Championship',
    Horse_HorseCompetition_WesternPleasure_Beginner_1st:
      'excels in Western Pleasure competitions andis achieved 1st place in the Beginner category',
    Horse_HorseCompetition_WesternPleasure_Beginner_2nd:
      'placed second in the beginner difficulty of the Western Pleasure horse competition',
    Horse_HorseCompetition_WesternPleasure_Beginner_3rd:
      'placed 3rd in the beginner level of the Western Pleasure horse competition',
    Horse_HorseCompetition_WesternPleasure_Expert_1st:
      'is an expert in Western Pleasure competitions andis consistently achieved 1st place',
    Horse_HorseCompetition_WesternPleasure_Expert_2nd:
      'is an expert in Western Pleasure competitions andis placed 2nd in a competition',
    Horse_HorseCompetition_WesternPleasure_Expert_3rd:
      'is an expert in Western Pleasure horse competitions andis achieved 3rd place',
    Horse_HorseCompetition_WesternPleasure_Intermediate_1st:
      'is an experienced Western Pleasure competitor andis achieved 1st place in intermediate level competitions',
    Horse_HorseCompetition_WesternPleasure_Intermediate_2nd:
      'is an accomplished Western Pleasure rider and placed 2nd in a competition at the intermediate level',
    Horse_HorseCompetition_WesternPleasure_Intermediate_3rd:
      'placed 3rd in an intermediate level Western Pleasure horse competition',
    Horse_HorseCompetition_WesternPleasure_Master_1st:
      'is a master of Western Pleasure competitions andis achieved 1st place',
    Horse_HorseCompetition_WesternPleasure_Master_2nd:
      'is a master of Western Pleasure competitions andis placed 2nd in their latest competition',
    Horse_HorseCompetition_WesternPleasure_Master_3rd:
      'is a master in Western Pleasure competitions, having achieved 3rd place',
    Horse_Personality_Aggressive: 'is aggressive',
    Horse_Personality_Brave: 'is brave',
    Horse_Personality_Defiant: 'is defiant',
    Horse_Personality_Energetic: 'is energetic',
    Horse_Personality_Fearful: 'is fearful',
    Horse_Personality_FreeSpirit: 'is a free spirit',
    Horse_Personality_Friendly: 'is friendly',
    Horse_Personality_Independent: 'is independent',
    Horse_Personality_Intelligent: 'is intelligent',
    Horse_Personality_Mellow: 'is mellow',
    Horse_Personality_Needy: 'is needy',
    HorseLover: 'is a Horse Lover',
    Hostile: 'is hostile and full of anger',
    HotHeaded: 'is hot-headed',
    HSExit_Dropout: 'is a high school dropout',
    HSExit_EarnedGED: 'is graduated with a GED',
    HSExit_Expelled: 'is expelled from High School',
    HSExit_Graduate_Early: 'is graduated from High School early',
    HSExit_Graduate_Honors: 'is graduated from High School with honors',
    HSExit_Graduate_Valedictorian: 'is a High School Valedictorian graduate',
    Humble: "is humbre and modest and doesn't express excessive pride",
    Human_Infant_Element_FrequentlyHiccups: 'frequently gets hiccups',
    Human_Infant_Element_FrequentlySneezes: 'frequently sneezes',
    Human_Infant_Element_Gassy: 'is a gassy infant',
    Human_Infant_Element_GoodAppetite: 'is a good appetite',
    Human_Infant_Element_HappySpitter: 'is a happy spitter',
    Human_Infant_Element_HatesBeingHeld: 'hates being held',
    Human_Infant_Element_HatesWakingUp: 'hates waking up',
    Human_Infant_Element_LovesBeingHeld: 'loves being held',
    Human_Infant_Element_LovesWakingUp: 'loves waking up',
    Human_Infant_Element_MessyEater: 'is a messy eater',
    Human_Infant_Element_ObsessedWithSound: 'is obsessed with sound',
    Human_Infant_Element_OnlySleepsWhenHeld: 'is a clingy sleeper',
    Human_Infant_Element_PeesDuringChanges: 'pees when clothes are changed',
    Human_Infant_Element_PeesDuringFeeding: 'pees when being fed',
    Human_Infant_Element_PickyEater: 'is a picky eater',
    Human_Infant_Element_RisesWithTheSun: 'is an early riser',
    Human_Infant_Element_SelfSoother: 'is a self-soother',
    Human_Infant_Element_Talker: 'is a chatty infant',
    Human_ToddlerPersonalityUpdate_Visible_Aggressive: 'is aggressive',
    Human_ToddlerPersonalityUpdate_Visible_AudioLover: 'loves audio',
    Human_ToddlerPersonalityUpdate_Visible_BookLover: 'loves books',
    Human_ToddlerPersonalityUpdate_Visible_Destructive: 'is destructive',
    Human_ToddlerPersonalityUpdate_Visible_EarlyRiser: 'is an early riser',
    Human_ToddlerPersonalityUpdate_Visible_GoodAppetite: 'has a good appetite',
    Human_ToddlerPersonalityUpdate_Visible_HatesBedtime: 'hates bedtime',
    Human_ToddlerPersonalityUpdate_Visible_HatesCarry: 'hates being carried',
    Human_ToddlerPersonalityUpdate_Visible_HatesWakeup: 'hates waking up',
    Human_ToddlerPersonalityUpdate_Visible_HeavySleeper: 'is a heavy sleeper',
    Human_ToddlerPersonalityUpdate_Visible_LightSleeper: 'is a light sleeper',
    Human_ToddlerPersonalityUpdate_Visible_LovesCarry: 'loves being carried',
    Human_ToddlerPersonalityUpdate_Visible_LovesWakeup: 'loves waking up',
    Human_ToddlerPersonalityUpdate_Visible_MessyEater: 'is a messy eater',
    Human_ToddlerPersonalityUpdate_Visible_PickyEater: 'is a picky eater',
    Human_ToddlerPersonalityUpdate_Visible_RunsAway:
      'is prone to running away when left unattended',
    Human_ToddlerPersonalityUpdate_Visible_Singer: 'is a talented singer',
    Human_ToddlerPersonalityUpdate_Visible_WaterLover: 'loves water activities',
    Humanoid_Robots_BehaviorModules_Childcare_Active:
      'is equipped with the Humanoid Robots Behavior Module for Childcare, making them an active caregiver that can take care of children efficiently',
    Humanoid_Robots_BehaviorModules_Childcare_NotLearned:
      'is not learned in childcare',
    Humanoid_Robots_BehaviorModules_ChildCare_TriggerUnlock:
      'is the Humanoid Robots Behavior Modules - Child Care Trigger Unlock trait',
    Humanoid_Robots_BehaviorModules_Cleaning_Active: 'is an Active Robo-Butler',
    Humanoid_Robots_BehaviorModules_Cleaning_NotLearned:
      'is not learned the cleaning behavior module and may not prioritize cleaning tasks',
    Humanoid_Robots_BehaviorModules_Cleaning_TriggerUnlock:
      'is unlocked the Cleaning Trigger behavior module, turning them into a Robo-Butler capable of efficiently tidying up any mess',
    Humanoid_Robots_BehaviorModules_Gardening_Active:
      'is the Humanoid Robots Behavior Module - Gardening Active trait. They excel in combining mechanical precision with a green thumb',
    Humanoid_Robots_BehaviorModules_Gardening_NotLearned:
      'is not learned the gardening skill and therefore cannot perform gardening tasks',
    Humanoid_Robots_BehaviorModules_Gardening_TriggerUnlock:
      'is unlocked the Gardening Behavior Module for their humanoid robot, enabling them to possess mechanical precision in their gardening skills. They have a skillful green thumb!',
    Humanoid_Robots_BehaviorModules_Party_Active: 'is an active party-goer',
    Humanoid_Robots_BehaviorModules_Party_NotLearned:
      'is the life of the party',
    Humanoid_Robots_BehaviorModules_Party_TriggerUnlock:
      'is unlocked the Party Trigger Behavior Module for their humanoid robot, turning them into the ultimate party machine! They can now turn up the music, grab a drink, and party the night away',
    Humanoid_Robots_BehaviorModules_Repair_Active:
      'is a handy-dandy repair bot',
    Humanoid_Robots_BehaviorModules_Repair_NotLearned: 'cannot repair objects',
    Humanoid_Robots_BehaviorModules_Repair_TriggerUnlock:
      's behavior module allows them to repair broken objects, preventing the need to hire a handyman',
    Humanoid_Robots_BehaviorModules_Security_Active:
      'is the active security behavior module',
    Humanoid_Robots_BehaviorModules_Security_NotLearned:
      'is not learned the security behavior module for humanoid robots',
    Humanoid_Robots_BehaviorModules_Security_TriggerUnlock:
      'is the Security Trigger Unlock trait',
    Humanoid_Robots_MainTrait:
      'is a humanoid robot with the main trait of being the loneliest',
    Hyper: 'tends to be very energized and has trouble getting focused',
    Iconic: 'is iconic',
    Impassive: 'has almost not emotions',
    Impulsive: 'is impulsive',
    IncrediblyFriendly: 'is incredibly friendly',
    Independent: 'is independent',
    Infant_Calm: 'is calm',
    Infant_Cautious: 'is cautious',
    Infant_Intense: 'is intense',
    Infant_Sensitive: 'is sensitive as an infant',
    Infant_Sunny: 'has a sunny disposition',
    Infant_Wiggly:
      'is always on the move and easily gets restless but may have difficulty staying focused or falling asleep',
    Insane: 'is insane',
    Insider: 'is an insider',
    InTheKnow: 'is In The Know',
    Introvert: 'is an introvert',
    Invested: 'is invested',
    IslandAncestors:
      'is connected to theislands of Sulani and can partake in their culture, summon elementals, and experience the blessings or consequences of their favor',
    Jealous: 'is jealous',
    Joyless: "is joyless, hasn't experienced joy for a long period of time",
    JungleExplorer_TreasureHunter:
      'is a skilled treasure hunter with a sharp eye for finding valuable relics in treasure chests',
    JungleExplorer_TreasureHunter_BG: 'is a Jungle Explorer Treasure Hunter',
    Kleptomaniac: 'is a kleptomaniac',
    Knowledge_SlingerOfSpells: 'is a Knowledge_SlingerOfSpells',
    LactoseIntolerant: 'is lactose intolerant',
    Lazy: 'is lazy',
    Legendary: 'is legendary',
    LifeSkills_Argumentative: 'is argumentative',
    LifeSkills_BadManners: 'is bad manners',
    LifeSkills_Compassionate: 'is compassionate',
    LifeSkills_EmotionalControl: 'is great emotional control',
    LifeSkills_GoodManners: 'is good manners',
    LifeSkills_Irresponsible: 'is irresponsible',
    LifeSkills_Mediator: 'is a skilled mediator',
    LifeSkills_Responsible: 'is responsible',
    LifeSkills_UncontrolledEmotion: 'is Uncontrolled Emotions',
    LifeSkills_Unfeeling: 'is unfeeling',
    Lifestyles_AdrenalineSeeker: 'is an Adrenaline Seeker',
    Lifestyles_CloseKnit: 'is a Close-Knit Lifestyle trait',
    Lifestyles_CoffeeFanatic: 'is a Coffee Fanatic',
    Lifestyles_Energetic: 'is an energetic lifestyle',
    Lifestyles_FrequentTraveler: 'is a frequent traveler',
    Lifestyles_HealthFoodNut: 'follows a Health Food Nut Lifestyle',
    Lifestyles_HungryForLove: 'is Hungry for Love',
    Lifestyles_Indoorsy: 'is a homebody',
    Lifestyles_JunkFoodDevourer: 'is a Junk Food Devourer',
    Lifestyles_Networker: 'is good at social networking',
    Lifestyles_NoNeedForRomance: 'doesnt need romance',
    Lifestyles_Outdoorsy: 'is outdoorsy',
    Lifestyles_Sedentary: 'is sedentary',
    Lifestyles_Techie: 'is a Techie',
    Lifestyles_Technophobe: 'is a technophobe',
    Lifestyles_Workaholic: 'is the Workaholic',
    'Light-Hearted': 'is light-hearted',
    LivingVicariously: 'is living vicariously',
    Loner: 'is a loner',
    Longevity: 'is the longevity trait',
    LovesOutdoors: 'loves the outdoors',
    Loyal: 'is loyal',
    Maker: 'is a Maker',
    makerNPC: 'is a maker',
    Marketable: 'is marketable',
    MasterMaker: 'is a MasterMaker',
    Mastermind: 'is a mastermind',
    MasterTrainer: 'is a Master Trainer',
    Materialistic: 'is materialistic',
    Mean: 'is mean',
    Melancholic: 'is melancholic, has a hard time getting daily tasks done',
    MeltMaster: 'is a Sandwich Melt Master',
    Memorable: 'is memorable',
    MentallyGifted: 'is mentally gifted',
    Mentor: 'is a mentor',
    Mischievous: 'is mischievous',
    Moody: 'is moody, can experience sudden mood swings',
    MorningPerson: 'is a Morning Person',
    Motivating: 'is motivating',
    Muser: 'is a muser',
    Music_Alternative: 'alternative music',
    Music_Americana: 'Americana music',
    Music_Backyard: 'music in the backyard',
    Music_Baroque: 'Baroque music',
    Music_Batuu: 'Batuu music',
    Music_Blues: 'blues music',
    Music_Brazilian: 'Brazilian music, particularly Carnival beats',
    Music_Classical: 'classical music',
    Music_CottageCore: 'Cottagecore music',
    Music_DJ: 'music from DJ booths',
    Music_EasyListening: 'listening to easy listening music',
    Music_Electronica: 'electronica music',
    Music_Focus:
      'is a strong preference for music and tends to focus better when listening to it',
    Music_HipHop: 'hip hop music',
    Music_Island: 'island music',
    Music_JapaneseFolk: 'listening to Japanese folk music',
    Music_Jazz: 'jazz music',
    Music_Kids: 'kids radio music',
    Music_Latin: 'Latin music',
    Music_LatinPop: 'listening to Latin pop music',
    Music_Lullabies: 'lullabies music',
    Music_Metal: 'metal music',
    Music_NewAge: 'listening to New Age music',
    Music_NuDisco: 'listening to NuDisco music',
    Music_Oldies: 'oldies music',
    Music_Pop: 'pop music',
    Music_Ranch: 'ranch music',
    Music_Retro: 'retro music',
    Music_RnB: 'R&B music',
    Music_Romance: 'music with a romantic theme',
    Music_SingerSongwriter: 'loves singer-songwriter music',
    Music_Spooky: 'spooky music',
    Music_SPop: 'S-Pop music',
    Music_StrangeTunes: 'strange tunes',
    Music_SummerStrut: 'listening to the Summer Strut music',
    Music_TweenPop: 'tween pop music',
    Music_WinterHoliday: 'Winter Holiday music',
    Music_World: 'world music',
    MusicLover: 'is a music lover',
    Nerdy: 'is nerdy',
    NaturalSpeaker: 'is a natural speaker',
    Nature_CountryCaretaker_NatureConversationalist:
      'is a Nature Conversationalist andis a special bond with animals, receives more gifts from rabbits and birds, and gets greater yields from plants. They also enjoy free grocery delivery and receive bill discounts while living in Henford-on-Bagley',
    Nature_InfluentialIndividual: 'is Nature Influential',
    Nature_MasterMixer: 'is a Nature Master Mixer',
    Neat: 'is neat',
    NectarKnowItAll: 'is a Nectar Know-It-All',
    NeedsNoOne: 'needs no one',
    Neurotic:
      'is neurotic, has higher sensitivity to sadness, anger and stress',
    NeverWeary: 'is never weary',
    NewInTown_InspiredExplorer: 'is a New in Town Inspired Explorer',
    NightOwl: 'is a Night Owl',
    NightOwl_CrystalHelmet: 'is a Night Owl',
    NosyNeighbor: 'is a Nosy Neighbor',
    Nurturing: 'is nurturing, becomes happy and calm around children',
    Observant: 'is observant',
    Occult_WitchOccult_BloodlineAncient:
      'is an Occult Witch with an Ancient Bloodline trait. They have stronger spellcasting abilities, gain extra talent points at each Spellcaster rank, and have a faster leveling rate. Additionally, they have a reduced chance of overloading while casting spells',
    Occult_WitchOccult_BloodlineStrong:
      'is an Occult Witch trait and a strong bloodline. They can gain extra talent points, earn Spellcaster experience faster, and have a reduced chance of overloading while casting spells',
    Occult_WitchOccult_BloodlineWeak:
      'is an Occult Witch trait with the Weak Bloodline. They are able to gain additional talent points, accumulate Spellcaster experience faster, and have a reduced chance of overloading spells',
    OccultWerewolf_AspirationTraits_BetterFuryControl:
      'is the Better Fury Control trait, which allows them to passively generate less Fury over time',
    OccultWerewolf_AspirationTraits_BetterTurning:
      'is the Better Turning trait',
    OccultWerewolf_AspirationTraits_FormerLycan:
      'is a former Lycan and can still experience the benefits of the Lunar Cycle and howl like before',
    OccultWerewolf_AspirationTraits_FriendlyWolf:
      'is the Friendly Wolf trait, which helps them build stronger relationships with both Werewolves and non-Werewolf people',
    OccultWerewolf_AspirationTraits_MoreFear:
      'is a threatening presence and can inspire fear in others',
    OccultWerewolf_DormantWolf:
      'is a dormant werewolf, with an inner wolf that remains asleep. It would take something significant to awaken their werewolf abilities',
    OccultWerewolf_GreaterWolfBlood:
      'possesses the OccultWerewolf_GreaterWolfBlood trait, which means they have been blessed with Greater Wolf Blood. This enhances their Werewolf growth and comes with high expectations',
    OccultWerewolf_InitiationBonusTrait:
      'is the OccultWerewolf_InitiationBonusTrait',
    OccultWerewolf_Temperaments_AntiCapitalistCanine:
      'is an Anti-Capitalist Canine',
    OccultWerewolf_Temperaments_BigBadWolf: 'is a Big Bad Wolf',
    OccultWerewolf_Temperaments_Carnivore: 'is a carnivorous werewolf',
    OccultWerewolf_Temperaments_EasyExcitable: 'is easy excitable',
    OccultWerewolf_Temperaments_FeelsOutcasted:
      'often feels outcasted and becomes furious when ignored or lacking social interaction. They may have a hard time feeling understood by others',
    OccultWerewolf_Temperaments_Frisky: 'is frisky',
    OccultWerewolf_Temperaments_GrumpyWolf:
      "can be grumpy at times, especially when they need their rest. It's best not to provoke them when they're feeling temperamental",
    OccultWerewolf_Temperaments_HatesBeingWet: 'hates being wet',
    OccultWerewolf_Temperaments_HungryLikeTheWolf:
      'is the Hungry Like The Wolf trait from the Occult Werewolf temperaments. They experience intense hunger and gain Fury when they are hungry. They may also have strong and sudden cravings at times',
    OccultWerewolf_Temperaments_Lunar_ForestMark:
      'bears the mark of the Lunar Forest, which reduces their Fury gains and Fun decay',
    OccultWerewolf_Temperaments_Lunar_HuntMark:
      'is the OccultWerewolf_Temperaments_Lunar_HuntMark trait',
    OccultWerewolf_Temperaments_Lunar_NightMark:
      'is the OccultWerewolf_Temperaments_Lunar_NightMark trait',
    OccultWerewolf_Temperaments_Lunar_WolfMark:
      'is the OccultWerewolf_Temperaments_Lunar_WolfMark trait',
    OccultWerewolf_Temperaments_MustBeClean: 'is the MustBeClean trait',
    OccultWerewolf_Temperaments_NightWolf:
      'is a Night Wolf and keeps a nocturnal cycle',
    OccultWerewolf_Temperaments_Prideful:
      'is prideful about being a Werewolf and may react strongly when their werewolf identity is questioned. They may become furious when feeling embarrassed or uncomfortable and can take things personally',
    OccultWerewolf_Temperaments_RestlessAnimal: 'is the Restless Animal trait',
    OccultWerewolf_Temperaments_SensitiveHearing:
      'is sensitive hearing as an Occult Werewolf',
    OccultWerewolf_Temperaments_SurvivalInstincts:
      'is survival instincts andis more aware of danger',
    OccultWerewolf_Temperaments_Territorial: 'is territorial',
    OccultWerewolf_Temperaments_WolfBrain:
      'is a Wolf Brain trait that affects their intellectual and logical pursuits due to their occult werewolf temperament',
    OccultWerewolf_Temperaments_WrackedWithGuilt: 'is wracked with guilt',
    OccultWerewolf_WerewolfAlly: 'is an ally of werewolves',
    Optimistic: 'is optimistic',
    OneWithNature: 'is One With Nature',
    Organizations_HonorSociety_Rank3: 'gains Mental skills faster',
    Outgoing: 'is outgoing',
    Overachiever: 'is an Overachiever',
    PaMatriarch:
      'is a PaMatriarch, providing skill boosts when they are around their children',
    Paranoid: 'is paranoid',
    PartyAnimal: 'is a party animal',
    PerfectHost: 'is a Perfect Host',
    Perfectionist: 'is a perfectionist',
    Pessimistic: 'is pessimistic',
    Pet_Active_Cat: 'is active',
    Pet_Active_Dog: 'is active',
    Pet_Aggressive_Cat: 'is aggressive',
    Pet_Aggressive_Dog: 'is aggressive',
    Pet_Curious_Cat: 'is curious',
    Pet_Curious_Dog: 'is curious',
    Pet_Friendly_Cat: 'is friendly',
    Pet_Friendly_Dog: 'is friendly',
    Pet_Glutton_Cat: 'is gluttonous',
    Pet_Glutton_Dog: 'is gluttonous',
    Pet_Hairy_Cat: 'is very hairy',
    Pet_Hairy_Dog: 'is very hairy',
    Pet_Hunter_Cat: 'is a skilled Hunter',
    Pet_Hunter_Dog: 'is a skilled Hunter',
    Pet_Independent_Cat: 'is independent',
    Pet_Independent_Dog: 'is independent',
    Pet_Lazy_Cat: 'is a lazy cat',
    Pet_Lazy_Dog: 'is a lazy dog',
    Pet_Loyal_Cat: 'is loyal',
    Pet_Loyal_Dog: 'is loyal',
    Pet_Naughty_Cat: 'is a naughty cat',
    Pet_Naughty_Dog: 'is a naughty dog',
    Pet_Playful_Cat: 'is a playful cat',
    Pet_Playful_Dog: 'is a playful dog',
    Pet_Skittish_Cat: 'is a skittish cat',
    Pet_Skittish_Dog: 'is a skittish dog',
    Pet_Smart_Cat: 'is a smart cat',
    Pet_Smart_Dog: 'is a smart dog',
    Pet_Stubborn_Cat: 'is a stubborn cat',
    Pet_Stubborn_Dog: 'is a stubborn dog',
    Pet_Vocal_Cat: 'is vocal',
    Pet_Vocal_Dog: 'is vocal',
    Pet_Wanderlust_Cat: 'is wanderlust',
    Pet_Wanderlust_Dog: 'is wanderlust',
    PhysicallyGifted: 'is physically gifted',
    Piper:
      'is a masterful Piper, using their melodious tunes to influence others',
    Player: 'is a player',
    PotionMaster: 'is a Potion Master',
    Practical: 'is practical',
    PregnancyOptions_Pet_canNotReproduce: 'cannot reproduce',
    PregnancyOptions_Pet_CanReproduce: 'can reproduce',
    PreparedVoyager: 'is a Prepared Voyager',
    ProfessionalSlacker: 'is a professional slacker',
    Proper: 'is proper',
    Quick_Learner: 'is a quick learner',
    Rancher: 'is a rancher',
    RecycleDisciple: 'is a Recycle Disciple',
    RegainedHumanity: 'is regained their humanity',
    Relatable: 'is relatable',
    Relaxed: 'is relaxed',
    reward_Child_Confidence_HighSelfEsteem: 'is high self-esteem',
    reward_Child_Confidence_LowSelfEsteem: 'is low self-esteem',
    Reward_HSTeam_CheerTeam:
      'excels in fitness and gains skill in that area quickly',
    Reward_HSTeam_ChessTeam: 'excels at Chess and can quickly gain Logic skill',
    Reward_HSTeam_ComputerTeam: 'gains programming skills faster',
    Reward_HSTeam_FootballTeam:
      'gains fitness skills faster due to their membership in the football team',
    Reward_Infant_Happy: 'is rewarded with happiness from their infancy',
    Reward_Infant_TopNotch: 'is top-notch',
    Reward_Infant_Unhappy: 'is rewarded by unhappiness from their infancy',
    Romantic: 'is romantic',
    SacredKnittingKnowledge: 'possesses sacred knitting knowledge',
    Salty: 'gets angry when embarrassed',
    Savant: 'is a savant',
    ScoutingAptitude: 'is a scouting aptitude',
    SeasonedGamer: 'is a seasoned gamer',
    'Short-temptered': 'gets angry and tense quickly',
    SeldomSleepy: 'is seldom sleepy',
    SelfAbsorbed: 'is self-absorbed',
    SelfAssured: 'is self-assured',
    'Self-Conscious': 'is self-conscious',
    Sensitive: 'is sensitive',
    Serious: 'is serious and not fond of joking',
    Shameless: 'is shameless',
    Shy: 'is shy',
    Sincere: 'is sincere',
    SleightofHand: 'can perform sleight of hand tricks',
    Slob: 'is a slob',
    'Slow-To-Warm-Up': 'is slow to warm up to new people',
    Smug: 'has excessive pride in their achievements, is very confident',
    Snob: 'is a snob',
    Sociable: 'is sociable',
    SociallyAwkward: 'is socially awkward',
    SociallyGifted: 'is socially gifted',
    SpeedCleaner: 'is a Speed Cleaner',
    SpeedReader: 'is a speed reader',
    SpiceHound: 'is a Spice Hound',
    Squeamish: 'is squeamish',
    SteelBladder: 'has the ability to hold their pee for a long time',
    'Stone-hearted': 'is indifferent and lacks understanding of emotions',
    Stormchaser: 'is a storm chaser',
    StovesAndGrillsMaster: 'is a Stove and Grill Master',
    Strangerville_Infected: 'is Strangerville Infected',
    SuperGreenThumb: 'is a Super Green Thumb',
    SuperParent_RoleModel: 'is a Super Parent Role Model',
    SupremeAuthority: 'has supreme authority',
    SurvivalInstinct: 'is a strong survival instinct',
    Survivalist: 'is a survivalist',
    TeenPranks_Prankster: 'is a Teen Prankster',
    Temperature_BurningMan: 'is unaffected by hot temperatures',
    Temperature_ColdAcclimation: 'is acclimated cold weather',
    Temperature_HeatAcclimation: 'is acclimated hot weather',
    Temperature_IceMan: 'is unaffected by cold temperatures',
    Tender: "is tender, gets sad when they're supposed to be angry",
    TheKnack: 'is The Knack trait',
    TheMaster:
      'is TheMaster, having supernatural control and the ability to always succeed with Command Powers on Vampire Offspring',
    'Thrill-seeking': 'is thrill-seeking',
    Timid: 'is timid',
    Toddler_Angelic: 'is angelic',
    Toddler_Charmer: 'is a Toddler Charmer',
    Toddler_Clingy: 'is clingy',
    Toddler_Fussy: 'is fussy',
    Toddler_Independent: 'is independent',
    Toddler_Inquisitive: 'is inquisitive',
    Toddler_Silly: 'is silly',
    Toddler_Wild: 'is wild',
    Top_Notch_Toddler: 'is a Top Notch Toddler',
    TrueMaster: 'is a True Master',
    Unflirty: 'is un-flirtatious',
    Unappeasable: 'is unappeasable',
    University_ArtHistoryDegreeBA: 'is a University Art History degree',
    University_ArtHistoryDegreeBAHonors:
      'is a University degree in Art History with Honors',
    University_ArtHistoryDegreeBS: 'is a University Art History Degree',
    University_ArtHistoryDegreeBSHonors:
      'is a University Art History Degree with Honors',
    University_BartenderDegree: 'is a University Bartender Degree',
    University_BiologyDegreeBA: 'is earned a degree in Biology',
    University_BiologyDegreeBAHonors:
      'is a Bachelor of Science degree in Biology with Honors',
    University_BiologyDegreeBS: 'is a University Biology Degree (BS)',
    University_BiologyDegreeBSHonors:
      'is a University Biology Degree with Honors',
    University_CommunicationsDegreeBA:
      'is a distinguished degree in Communications',
    University_CommunicationsDegreeBAHonors:
      'is a University Communications Degree with Honors',
    University_CommunicationsDegreeBS: 'is a degree in Communications',
    University_CommunicationsDegreeBSHonors:
      'is a degree in Communications with Honors',
    University_ComputerScienceDegreeBA: 'is a computer science degree',
    University_ComputerScienceDegreeBAHonors:
      'is a Computer Science Degree with Honors',
    University_ComputerScienceDegreeBS:
      'is a University Computer Science Degree',
    University_ComputerScienceDegreeBSHonors:
      'is earned a Distinguished Degree in Computer Science with Honors',
    University_CulinaryArtsDegreeBA:
      'is earned a Distinguished Degree in Culinary Arts',
    University_CulinaryArtsDegreeBAHonors:
      'is a University Culinary Arts Degree with Honors',
    University_CulinaryArtsDegreeBS: 'is a University Culinary Arts Degree',
    University_CulinaryArtsDegreeBSHonors:
      "is a Bachelor's Degree in Culinary Arts with Honors",
    University_DramaDegreeBA: 'is a Distinguished Degree in Drama',
    University_DramaDegreeBAHonors: 'is a University Drama Degree with Honors',
    University_DramaDegreeBS: 'is earned a degree in Drama',
    University_DramaDegreeBSHonors:
      'is a University Degree in Drama with Honors',
    University_EconomicsDegreeBA: 'is a University_EconomicsDegreeBA',
    University_EconomicsDegreeBAHonors:
      "is a Bachelor's degree in Economics with Honors",
    University_EconomicsDegreeBS: 'is a university degree in Economics',
    University_EconomicsDegreeBSHonors:
      'is a University Economics Degree with Honors',
    University_FineArtDegreeBA: 'is a University Fine Art Degree',
    University_FineArtDegreeBAHonors:
      'is a University Fine Art Degree with Honors',
    University_FineArtDegreeBS: 'is a University Fine Arts Degree',
    University_FineArtDegreeBSHonors:
      'is a University Fine Art Degree with Honors',
    University_HigherEducation:
      'is highly educated and skilled in utilizing their university experience',
    University_HistoryDegreeBA: 'is a University History Degree BA',
    University_HistoryDegreeBAHonors: 'is a University_HistoryDegreeBAHonors',
    University_HistoryDegreeBS: 'is a History degree',
    University_HistoryDegreeBSHonors:
      "is earned a Bachelor's Degree in History with Honors",
    University_LanguageAndLiteratureDegreeBA:
      'is a University Language and Literature Degree (BA)',
    University_LanguageAndLiteratureDegreeBAHonors:
      'is a University Language and Literature Degree with Honors',
    University_LanguageAndLiteratureDegreeBS:
      'is a Language & Literature degree from university',
    University_LanguageAndLiteratureDegreeBSHonors:
      'is a University degree in Language & Literature with Honors',
    University_PhysicsDegreeBA: 'is earned a Degree in Physics',
    University_PhysicsDegreeBAHonors:
      "is a Bachelor's Degree in Physics with Honors",
    University_PhysicsDegreeBS: 'is earned a Distinguished Degree in Physics',
    University_PhysicsDegreeBSHonors:
      'is a University Degree in Physics with Honors',
    University_PsychologyDegreeBA: 'is earned a degree in Psychology',
    University_PsychologyDegreeBAHonors:
      'is a degree in Psychology with honors',
    University_PsychologyDegreeBS: 'is a University Psychology Degree',
    University_PsychologyDegreeBSHonors:
      'is a University Degree in Psychology with Honors',
    University_VillainyDegreeBA: 'is a Degree in Villainy',
    University_VillainyDegreeBAHonors: 'is a degree in Villainy with honors',
    University_VillainyDegreeBS: 'is a University Villainy graduate',
    University_VillainyDegreeBSHonors:
      'is achieved a Distinguished Degree in Villainy with Honors',
    Unpredictable: 'is unpredictable',
    Unstable: 'is mentally unstable',
    UnstoppableFame: 'is unstoppable in their fame',
    Untroubled: 'is untroubled',
    ValuedCustomer: 'is a valued customer',
    Vegetarian: 'is a vegetarian',
    Waterproof: 'is waterproof',
    WebMaster: 'is a WebMaster',
    'Well-Balanced':
      'is emotionally stable and good at handling negative emotions',
    WerewolfPack_FriendA: 'is a Friend of the Werewolf Pack',
    WerewolfPack_FriendB: 'is a friend of the Werewolf Pack',
    WorldlyKnowledge: 'is knowledgeable in worldly matters',
    WorldRenownedActor: 'is a world-renowned actor',
    Mood_Angry: 'is feeling angry',
    Mood_Bored: 'is feeling bored',
    Mood_Confident: 'is feeling confident',
    Mood_Embarrassed: 'is feeling embarrassed',
    Mood_Energized: 'is feeling energized',
    Mood_Fine: 'is feeling fine',
    Mood_Flirty: 'is feeling flirty',
    Mood_Focused: 'is feeling focused',
    Mood_Happy: 'is feeling happy',
    Mood_Inspired: 'is feeling inspired',
    Mood_Playful: 'is feeling playful',
    Mood_Sad: 'is feeling sad',
    Mood_Dazed: 'is feeling dazed',
    Mood_Stressed: 'is feeling stressed',
    Mood_Uncomfortable: 'is feeling uncomfortable',
    Mood_Asleep: 'is feeling asleep',
    mood_Hyper_Pets: 'is feeling hyper',
    mood_Drowsy_Cat: 'is feeling drowsy',
    mood_Excited_Dog: 'is feeling excited',
    mood_Asleep_Dog: 'is feeling asleep',
    mood_Mopey_Dog: 'is feeling mopey',
    mood_Anxious_Dog: 'is feeling anxious',
    mood_Angry_Dog: 'is feeling angry',
    mood_Fine_Dog: 'is feeling fine',
    mood_Flirty_Dog: 'is feeling flirty',
    mood_Scared_Dog: 'is feeling scared',
    mood_Happy_Dog: 'is feeling happy',
    mood_Sad_Dog: 'is feeling sad',
    mood_Ashamed_Dog: 'is feeling ashamed',
    mood_Anxious_Cat: 'is feeling anxious',
    mood_Angry_Cat: 'is feeling angry',
    mood_Flirty_Cat: 'is feeling flirty',
    mood_Scared_Cat: 'is feeling scared',
    mood_Happy_Cat: 'is feeling happy',
    mood_Asleep_Cat: 'is feeling asleep',
    mood_Fine_Cat: 'is feeling fine',
    Mood_Possessed: 'is currently possessed',
    mood_Recharging: 'is low on energy and is recharging',
    Mood_Scared: 'is feeling scared',
    Mood_Horse_Happy: 'is feeling happy',
    mood_Horse_Uncomfortable: 'is feeling uncomfortable',
    mood_Horse_Scared: 'is feeling scared',
    mood_Horse_Angry: 'is feeling angry',
    mood_Horse_Asleep: 'is feeling asleep',
    mood_Horse_Dazed: 'is feeling dazed',
    mood_Horse_Fine: 'is feeling fine',
    mood_Horse_Confident: 'is feeling confident',
    mood_Horse_Tense: 'is feeling tense',
    mood_Horse_Sad: 'is feeling sad',
  })
);
