// GENERATED by scripts/gen-tier-index.ts --tier core. Do not edit by hand.
// The committed form is the dev one; a stripped build regenerates it for its tier.
import type { Tier } from 'main/sentient-sims/tiers/types';
import type { RendererTier } from './types';

export const TIER: Tier = 'core';
export const RENDERER_TIERS: RendererTier[] = [];
