// Writes the two generated tier index modules for one build tier:
//   src/main/sentient-sims/tiers/index.ts   (TIER, TIER_STAMP, TIER_REGISTRATIONS)
//   src/renderer/tiers/index.tsx            (TIER, RENDERER_TIERS)
//
// Rollup fails hard on an import it cannot resolve, static or dynamic, so a build that has
// deleted a tier's entry module needs an index that never names it. The committed form is
// the dev one (Tiers.test.ts pins it to this generator's output); strip-tree.ts regenerates
// both for core and stream.
//
//   node scripts/gen-tier-index.ts --tier dev|stream|core [--check]
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { argValue, keptLayers, parseTier, repoRoot, tierStamp, type Layer, type Tier } from './tiers.ts';

export const MAIN_INDEX = 'src/main/sentient-sims/tiers/index.ts';
export const RENDERER_INDEX = 'src/renderer/tiers/index.tsx';

const MAIN_EXPORTS: Record<Layer, string> = {
  stream: 'streamTier',
  autonomy: 'autonomyTier',
  dev: 'devTier',
};

const RENDERER_EXPORTS: Record<Layer, string> = {
  stream: 'streamRendererTier',
  autonomy: 'autonomyRendererTier',
  dev: 'devRendererTier',
};

function header(tier: Tier): string {
  return [
    `// GENERATED by scripts/gen-tier-index.ts --tier ${tier}. Do not edit by hand.`,
    '// The committed form is the dev one; a stripped build regenerates it for its tier.',
  ].join('\n');
}

export function renderMainIndex(tier: Tier): string {
  const layers = keptLayers(tier);
  const imports = layers.map((layer) => `import { ${MAIN_EXPORTS[layer]} } from './${layer}';`);
  const list = layers.map((layer) => MAIN_EXPORTS[layer]).join(', ');
  return [
    header(tier),
    "import type { Tier, TierRegistration } from './types';",
    ...imports,
    '',
    `export const TIER: Tier = '${tier}';`,
    `export const TIER_STAMP = '${tierStamp(tier)}';`,
    `export const TIER_REGISTRATIONS: TierRegistration[] = [${list}];`,
    '',
  ].join('\n');
}

export function renderRendererIndex(tier: Tier): string {
  const layers = keptLayers(tier);
  const imports = layers.map((layer) => `import { ${RENDERER_EXPORTS[layer]} } from './${layer}';`);
  const list = layers.map((layer) => RENDERER_EXPORTS[layer]).join(', ');
  return [
    header(tier),
    "import type { Tier } from 'main/sentient-sims/tiers/types';",
    "import type { RendererTier } from './types';",
    ...imports,
    '',
    `export const TIER: Tier = '${tier}';`,
    `export const RENDERER_TIERS: RendererTier[] = [${list}];`,
    '',
  ].join('\n');
}

export function expectedIndexes(tier: Tier): Record<string, string> {
  return {
    [MAIN_INDEX]: renderMainIndex(tier),
    [RENDERER_INDEX]: renderRendererIndex(tier),
  };
}

export function writeIndexes(tier: Tier, root: string = repoRoot): string[] {
  const written: string[] = [];
  for (const [relative, content] of Object.entries(expectedIndexes(tier))) {
    const target = path.join(root, relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
    written.push(relative);
  }
  return written;
}

export function checkIndexes(tier: Tier, root: string = repoRoot): string[] {
  const stale: string[] = [];
  for (const [relative, content] of Object.entries(expectedIndexes(tier))) {
    const target = path.join(root, relative);
    const actual = fs.existsSync(target) ? fs.readFileSync(target, 'utf-8') : '';
    if (actual !== content) {
      stale.push(relative);
    }
  }
  return stale;
}

function main(argv: string[]) {
  const tier = parseTier(argValue(argv, '--tier') ?? 'dev');
  if (argv.includes('--check')) {
    const stale = checkIndexes(tier);
    if (stale.length > 0) {
      console.error(`tier index out of date for --tier ${tier}: ${stale.join(', ')}`);
      process.exit(1);
    }
    console.log(`tier index matches --tier ${tier}`);
    return;
  }
  for (const written of writeIndexes(tier)) {
    console.log(`wrote ${written} (--tier ${tier})`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
